import type { Trip } from './types';

export const trips: Trip[] = [
  {
    id: '1',
    slug: 'gokarna-beach-getaway',
    name: 'Gokarna Beach Getaway',
    tagline: 'Sun, Sand, and Self-Discovery',
    price: 5499,
    image: 'gokarna-1',
    shortDescription: 'Crashing waves, starry skies, and strangers who become your travel tribe. This is Gokarna the Getrippin’ way. A place where you’ll sleep under the stars, wake to salt wind, and forget your notifications exist.',
    duration: '2D/3N',
    tripType: 'Beach',
    difficulty: 'Easy',
    idealFor: ['Solo', 'Groups', 'Couples'],
    highlights: [
      'Legendary beach trek from Paradise to Om Beach',
      'Cliffside cafes with stunning sunset views',
      'Optional surfing and kayaking lessons',
      'Bonfire nights with music and stories',
      'Visit to the historic Mirjan Fort',
      'Vibrant community of fellow travelers'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Departure from Bangalore', details: 'Meet the group and depart from Bangalore around 9:30 PM. We travel overnight in a comfortable AC Tempo Traveler.' },
      { day: 'Day 1 (Saturday)', icon: 'sun', title: 'Beach Trek & Sunset Cafes', details: 'Arrive in Gokarna, check into our stay, and fuel up with breakfast. Embark on the iconic beach trek from Paradise to Om Beach. End the day at a clifftop cafe watching a magical sunset.' },
      { day: 'Day 2 (Sunday)', icon: 'kayak', title: 'Water Sports & Fort Exploration', details: 'Morning is for adventure! Choose optional surfing or kayaking lessons. Later, we explore the ancient Mirjan Fort before starting our return journey to Bangalore by 8 PM.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Arrival in Bangalore', details: 'Arrive back in Bangalore around 6 AM, refreshed and with a bag full of memories.' },
    ],
    inclusions: ['AC Tempo Traveler', 'Stay (Homestay/Hostel)', '2 Breakfasts, 1 Dinner', 'Trip Captain & Guide', 'All entry fees'],
    exclusions: ['Lunches & 1 Dinner', 'Optional Add-ons (Surfing/Kayaking)', 'Personal Expenses'],
    pickupPoints: ['Yeshwanthpur Metro', 'Hebbal Flyover', 'Nelamangala Toll', 'Rajajinagar', 'Kengeri'],
    gallery: ["gokarna-2", "gokarna-3", "gokarna-4", "gokarna-5", "gokarna-6"],
    addons: [
      { name: "Surfing Lesson", price: 1200 },
      { name: "Kayaking", price: 800 }
    ],
    upcomingDates: ["July 12", "July 19", "July 26", "August 2"]
  },
  {
    id: '2',
    slug: 'coorg-coffee-trails',
    name: 'Coorg Coffee Trails',
    tagline: 'Into the Scotland of India',
    price: 5299,
    image: 'coorg-1',
    shortDescription: 'Wake up to the aroma of fresh coffee, chase misty waterfalls, and find your peace in the rolling green hills. This isn’t just a trip; it’s a sensory journey into the heart of Karnataka’s coffee country.',
    duration: '2D/2N',
    tripType: 'Trek',
    difficulty: 'Easy',
    idealFor: ['Groups', 'Couples'],
     highlights: [
      'Guided tour of a lush coffee plantation',
      'Visit the majestic Abbey Falls',
      'Panoramic sunset views from Raja\'s Seat',
      'Encounter gentle giants at Dubare Elephant Camp',
      'Explore the peaceful Tibetan settlement of Bylakuppe',
      'Stay in a cozy, authentic Coorgi homestay'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Overnight journey to Coorg', details: 'Depart from Bangalore around 10:00 PM, leaving the city chaos behind.' },
      { day: 'Day 1 (Saturday)', icon: 'coffee', title: 'Waterfalls & Coffee Estates', details: 'Arrive in Coorg and check in. Visit the stunning Abbey Falls, explore a local coffee plantation, and end the day at Raja\'s Seat for a breathtaking sunset.' },
      { day: 'Day 2 (Sunday)', icon: 'plus', title: 'Elephants, Monasteries & Departure', details: 'A morning trip to Dubare Elephant Camp, followed by the tranquility of the Tibetan Golden Temple at Bylakuppe. We depart for Bangalore in the afternoon.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Arrival in Bangalore', details: 'Arrive back in Bangalore early morning, with the taste of fresh coffee still lingering.' },
    ],
    inclusions: ['AC Transportation', 'Authentic Homestay', '2 Breakfasts, 1 Dinner', 'Trip Captain', 'All Entry Fees'],
    exclusions: ['Lunches', 'Elephant Camp Activities', 'Personal Expenses'],
    pickupPoints: ['Silk Board', 'Banashankari', 'Nayandahalli', 'Jayanagar'],
    gallery: ["coorg-2", "coorg-3", "coorg-4"],
    addons: [],
    upcomingDates: ["July 12", "July 26", "August 9"]
  },
   {
    id: '3',
    slug: 'wayanad-nature-escape',
    name: 'Wayanad Nature Escape',
    tagline: 'Lush Hills & Ancient Caves',
    price: 5299,
    image: 'wayanad-1',
    shortDescription: 'Trade cityscapes for misty hills and concrete jungles for ancient caves. In Wayanad, every view is a painting, and every path leads to a new discovery. This is your green paradise.',
    duration: '2D/2N',
    tripType: 'Trek',
    difficulty: 'Moderate',
    idealFor: ['Solo', 'Groups'],
    highlights: [
      'Hike to the heart-shaped lake on Chembra Peak',
      'Explore ancient history in the Edakkal Caves',
      'Witness the breathtaking Soochipara Waterfalls',
      'Enjoy panoramic views from Lakkidi View Point',
      'Relax with boating on Pookode Lake',
      'Cozy bonfires under starry skies'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Journey to the Hills', details: 'Departure from Bangalore by AC tempo traveler (10 PM), rolling towards the misty hills of Kerala.' },
      { day: 'Day 1 (Saturday)', icon: 'container', title: 'Waterfalls, Viewpoints & Bonfire', details: 'Arrive in Wayanad, check-in, and enjoy breakfast. Visit the cascading Soochipara Waterfalls and the stunning Lakkidi View Point. End the day with a cozy bonfire.' },
      { day: 'Day 2 (Sunday)', icon: 'sun', title: 'Ancient Caves & Serene Lakes', details: 'Post-breakfast, we trek to the historic Edakkal Caves to see ancient petroglyphs. Enjoy a peaceful boating session at Pookode Lake before we depart for Bangalore.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Arrival in Bangalore', details: 'Arrive back in Bangalore, carrying memories of the misty green paradise.' },
    ],
    inclusions: ['AC tempo traveler transport', 'Stay in a beautiful resort', '2 Breakfasts & 1 Dinner', 'All entry fees & guide charges', 'Trip Captain'],
    exclusions: ['Lunches & 1 Dinner', 'Boating charges', 'Personal expenses'],
    pickupPoints: ['Silk Board', 'Banashankari', 'Nayandahalli', 'Jayanagar'],
    gallery: ["wayanad-2", "wayanad-3", "wayanad-4", "wayanad-5", "wayanad-6"],
    addons: [],
    upcomingDates: ["July 19", "August 2", "August 16"]
  },
  {
    id: '4',
    slug: 'sakleshpur-waterfall-camp',
    name: 'Sakleshpur Waterfall Camp',
    tagline: 'Trek, Camp, Repeat',
    price: 4999,
    image: 'sakleshpur-1',
    shortDescription: 'For those who hear the call of the wild. An adventure-packed weekend with a trek to a private waterfall, riverside camping, and cozy bonfires under a blanket of stars. This is where you disconnect to reconnect.',
    duration: '2D/2N',
    tripType: 'Camp',
    difficulty: 'Easy',
    idealFor: ['Solo', 'Groups'],
    highlights: [
      'Exclusive trek to a private waterfall',
      'Riverside camping with bonfire and music',
      'Explore the unique star-shaped Manjarabad Fort',
      'Off-road jeep ride experience',
      'Panoramic views of the Western Ghats',
      'Stargazing away from city lights'
    ],
    itinerary: [
        { day: 'Day 0 (Friday)', icon: 'bus', title: 'Departure to Sakleshpur', details: 'Leave from Bangalore at 10 PM, ready for a weekend of adventure.' },
        { day: 'Day 1 (Saturday)', icon: 'container', title: 'Waterfall Trek & Riverside Camping', details: 'Reach our campsite, freshen up, and trek to a stunning private waterfall. The evening is for campfire stories, music, and dinner.' },
        { day: 'Day 2 (Sunday)', icon: 'sun', title: 'Manjarabad Fort & Return', details: 'After breakfast, we visit the historic star-shaped Manjarabad Fort for incredible views of the Western Ghats before starting our journey back to Bangalore.' },
        { day: 'Day 3 (Monday)', icon: 'home', title: 'Back to City Life', details: 'Arrive in Bangalore early morning, with stories to tell.' },
    ],
    inclusions: ['AC Transportation', 'Riverside Camping/Homestay', '2 Breakfasts, 1 Dinner', 'Trek Guide', 'Bonfire & Music'],
    exclusions: ['Lunches', 'Personal Expenses', 'Anything not mentioned in inclusions'],
    pickupPoints: ['Yeshwanthpur Metro', 'Hebbal Flyover', 'Nelamangala Toll'],
    gallery: ["sakleshpur-2", "sakleshpur-3", "sakleshpur-4"],
    addons: [],
    upcomingDates: ["July 12", "July 26", "August 9"]
  },
  {
    id: '5',
    slug: 'chikmagalur-chill-trek',
    name: 'Chikmagalur Chill & Trek',
    tagline: 'Hills, Waterfalls, and Coffee',
    price: 5499,
    image: 'chikmagalur-1',
    shortDescription: 'Breathe in the fragrance of coffee, conquer Karnataka\'s highest peak, and let the cool spray of waterfalls wash your worries away. This is the perfect blend of thrill and chill.',
    duration: '2D/2N',
    tripType: 'Trek',
    difficulty: 'Moderate',
    idealFor: ['Solo', 'Groups', 'Couples'],
    highlights: [
      'Trek to Mullayanagiri, the highest peak in Karnataka',
      'Visit the beautiful Jhari (Buttermilk) Waterfalls',
      'Explore a serene, aromatic coffee estate',
      'Witness stunning sunset/sunrise views from the peaks',
      'Stay in a homestay with scenic views',
      'Experience the heartland of Indian coffee'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Departure to Chikmagalur', details: 'Depart from Bangalore around 10:00 PM.' },
      { day: 'Day 1 (Saturday)', icon: 'sun', title: 'Mullayanagiri Peak & Jhari Falls', details: 'Reach Chikmagalur, check-in, and start the exhilarating trek to Mullayanagiri peak. Later, we rejuvenate at the beautiful Jhari Waterfalls.' },
      { day: 'Day 2 (Sunday)', icon: 'coffee', title: 'Coffee Plantation & Departure', details: 'Explore a serene coffee estate, learn about the journey from bean to cup, and enjoy the scenic drive back to Bangalore.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Return to Bangalore', details: 'Arrive in Bangalore early morning, fully recharged.' },
    ],
    inclusions: ['AC Transportation', 'Homestay with a view', '2 Breakfasts, 1 Dinner', 'Trek Guide', 'All Entry Fees'],
    exclusions: ['Lunches', 'Jeep ride charges (if any)', 'Personal Expenses'],
    pickupPoints: ['Silk Board', 'Banashankari', 'Nayandahalli', 'Jayanagar'],
    gallery: ["chikmagalur-2", "chikmagalur-3", "chikmagalur-4"],
    addons: [],
    upcomingDates: ["July 19", "August 2", "August 16"]
  },
  {
    id: '6',
    slug: 'dandeli-adventure-camp',
    name: 'Dandeli Adventure Camp',
    tagline: 'Where the Thrill Begins',
    price: 5999,
    image: 'dandeli-1',
    shortDescription: 'Answer the call of the wild. Get your adrenaline pumping with white water rafting, kayaking, and jungle adventures in the untamed heart of Dandeli. This is not a vacation; it’s an expedition.',
    duration: '2D/3N',
    tripType: 'Adventure',
    difficulty: 'Moderate',
    idealFor: ['Solo', 'Groups'],
    highlights: [
      'Thrilling white water rafting in the Kali river',
      'Kayaking and zorbing sessions',
      'Jungle trek to spot local flora and fauna',
      'Experience a natural jacuzzi bath in the river',
      'Riverside camping with bonfire',
      'Adrenaline-pumping ziplining (optional)'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Overnight to Dandeli', details: 'Leave from Bangalore around 9:00 PM, geared up for an action-packed weekend.' },
      { day: 'Day 1 (Saturday)', icon: 'kayak', title: 'River Rafting & Water Sports', details: 'Arrive at our riverside campsite. Post breakfast, we hit the water for an exciting session of white water rafting, kayaking, and zorbing.' },
      { day: 'Day 2 (Sunday)', icon: 'sun', title: 'Jungle Trek & Natural Jacuzzi', details: 'Start the day with a jungle trek. Later, relax in the natural jacuzzi formed by the Kali river. We depart for Bangalore in the evening.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Back to Bangalore', details: 'Arrive in Bangalore by morning, with tales of adventure.' },
    ],
    inclusions: ['AC Transportation', 'Riverside Camp Stay', '2 Breakfasts, 1 Lunch, 1 Dinner', 'Rafting & included water activities', 'Forest Entry Fees'],
    exclusions: ['1 Lunch', 'Optional activities like Zipline', 'Personal Expenses'],
    pickupPoints: ['Yeshwanthpur Metro', 'Hebbal Flyover', 'Nelamangala Toll'],
    gallery: ["dandeli-2", "dandeli-3", "dandeli-4"],
    addons: [{ name: "Zipline", price: 500 }],
    upcomingDates: ["July 12", "August 9", "September 6"]
  },
  {
    id: '7',
    slug: 'varkala-coastal-escape',
    name: 'Varkala Coastal Escape',
    tagline: 'Cliffs, Coconuts & Cool Vibes',
    price: 6299,
    image: 'varkala-1',
    shortDescription: 'Discover a different side of the coast. Where red cliffs kiss the Arabian Sea, vibrant cafes buzz with energy, and the vibe is unapologetically chill. Varkala is a feeling, and you’re invited to feel it.',
    duration: '2D/3N',
    tripType: 'Beach',
    difficulty: 'Easy',
    idealFor: ['Solo', 'Couples', 'Groups'],
    highlights: [
        'Explore the famous Varkala Cliff and its vibrant cafes',
        'Relax on the golden sands of Papanasam Beach',
        'Kayaking in the serene Kappil backwaters',
        'Visit the ancient Janardanaswamy Temple',
        'Stunning sunset views from the clifftop',
        'Optional Yoga and surfing sessions'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Journey to the Coast', details: 'Take an overnight train/bus from Bangalore to Varkala, dreaming of the sea.' },
      { day: 'Day 1 (Saturday)', icon: 'sun', title: 'Varkala Cliff & Beach Life', details: 'Arrive in Varkala, check into our stay near the cliff. Spend the day exploring the unique cliff, browsing shops, and relaxing by Papanasam Beach.' },
      { day: 'Day 2 (Sunday)', icon: 'kayak', title: 'Backwaters, Temples & Sunset', details: 'Morning trip to Kappil Lake for a peaceful backwater kayaking experience. Visit the ancient Janardanaswamy Temple and enjoy a final, spectacular sunset from the cliff.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Return Journey', details: 'Depart from Varkala for the overnight journey, arriving back in Bangalore on Monday morning.' },
    ],
    inclusions: ['Train/Bus tickets (to & fro)', 'Stay near the cliff', '2 Breakfasts', 'Trip Captain', 'Kayaking charges'],
    exclusions: ['All lunches and dinners', 'Local auto/cab fares', 'Personal expenses'],
    pickupPoints: ['Majestic Railway Station', 'Madiwala (for bus)'],
    gallery: ["varkala-2", "varkala-3", "varkala-4"],
    addons: [],
    upcomingDates: ["August 15", "September 13", "October 11"]
  },
  {
    id: '8',
    slug: 'murudeshwar-honnavar-escape',
    name: 'Murudeshwar & Honnavar Escape',
    tagline: 'Gods, Giants, and Glowing Waters',
    price: 5799,
    image: 'murudeshwar-1',
    shortDescription: 'A journey of epic proportions. Witness the world’s second-tallest Shiva statue, glide through mystical mangrove forests, and discover beaches that feel like a secret. This trip is a story waiting to be told.',
    duration: '2D/3N',
    tripType: 'Beach',
    difficulty: 'Easy',
    idealFor: ['Groups', 'Couples'],
    highlights: [
      'Marvel at the giant Shiva statue in Murudeshwar',
      'Explore the serene Sharavathi Kandla Mangrove Boardwalk',
      'Discover the hidden Apsarakonda waterfalls',
      'Relax on pristine, untouched beaches',
      'Boating in the Honnavar backwaters',
      'Stunning views of Netrani Island'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Departure from Bangalore', details: 'Start the overnight journey from Bangalore around 9:00 PM.' },
      { day: 'Day 1 (Saturday)', icon: 'sun', title: 'Murudeshwar & Netrani Views', details: 'Reach Murudeshwar, and be awestruck by the giant Shiva statue and temple complex. Relax on the beach with beautiful views of Netrani Island.' },
      { day: 'Day 2 (Sunday)', icon: 'kayak', title: 'Honnavar Backwaters & Apsarakonda', details: 'Explore the famous mangrove boardwalk in Honnavar. Later, we visit the enchanting Apsarakonda waterfalls before departing for Bangalore.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Arrive in Bangalore', details: 'Reach Bangalore in the morning, with a sense of wonder.' },
    ],
    inclusions: ['AC Tempo Traveler', 'Beachside Stay', '2 Breakfasts, 1 Dinner', 'Trip Captain', 'All Entry Fees'],
    exclusions: ['Lunches', 'Boating charges in Honnavar', 'Personal Expenses'],
    pickupPoints: ['Yeshwanthpur Metro', 'Hebbal Flyover', 'Nelamangala Toll'],
    gallery: ["murudeshwar-2", "murudeshwar-3", "murudeshwar-4"],
    addons: [],
    upcomingDates: ["July 26", "August 23", "September 20"]
  },
  {
    id: '9',
    slug: 'kudremukh-trek-expedition',
    name: 'Kudremukh Trek Expedition',
    tagline: 'Conquer the Horse-Faced Peak',
    price: 5499,
    image: 'kudremukh-1',
    shortDescription: 'This is more than a trek; it’s a challenge. A journey across rolling green hills, dense shola forests, and misty peaks. If you want to earn your views and test your limits, Kudremukh is calling.',
    duration: '2D/2N',
    tripType: 'Trek',
    difficulty: 'Hard',
    idealFor: ['Solo', 'Groups'],
    highlights: [
        'One of Karnataka\'s most beautiful and challenging treks (22kms)',
        'Traverse through rolling green hills and dense shola forests',
        'Stunning panoramic views from the summit',
        'Chance to spot diverse wildlife',
        'Stay at a rustic homestay at the base',
        'A true test of endurance and spirit'
    ],
    itinerary: [
      { day: 'Day 0 (Friday)', icon: 'bus', title: 'Journey to the Base', details: 'Depart from Bangalore for the Kudremukh base camp, preparing for the challenge ahead.' },
      { day: 'Day 1 (Saturday)', icon: 'sun', title: 'The Kudremukh Trek (22kms)', details: 'Start the trek early morning. The challenging trail takes you through stunning landscapes of rolling grasslands and forests. Reach the peak, have packed lunch with a view, and descend by evening.' },
      { day: 'Day 2 (Sunday)', icon: 'container', title: 'Recovery & Return', details: 'Relax your tired muscles with a visit to a nearby cool stream or waterfall. Post-lunch, we start our journey back to Bangalore.' },
      { day: 'Day 3 (Monday)', icon: 'home', title: 'Back to Urban Life', details: 'Arrive in Bangalore early morning, with an unbeatable sense of accomplishment.' },
    ],
    inclusions: ['AC Tempo Traveler', 'Homestay/Dormitory Stay', 'All Meals (2 Breakfasts, 1 Packed Lunch, 1 Dinner)', 'Forest Permits & Guide', 'Trip Captain'],
    exclusions: ['1 Lunch on Day 2', 'Personal Expenses', 'Anything not mentioned in inclusions'],
    pickupPoints: ['Yeshwanthpur Metro', 'Hebbal Flyover', 'Nelamangala Toll'],
    gallery: ["kudremukh-2", "kudremukh-3", "kudremukh-4"],
    addons: [],
    upcomingDates: ["July 19", "August 16", "September 13"]
  }
];
